config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'items#index'
  resources :items, param: :slug
  resources :charges, :cartcontents, :orders
  post "add", to: "cartcontents#add"
  post "remove", to: "cartcontents#remove"
  get '/mail', to: 'items#mail'
end

app/models/cartcontent.rb
class Cartcontent < ApplicationRecord
    belongs_to :user
    belongs_to :item
end

app/controllers/cartcontents_controller.rb
class CartcontentsController < ApplicationController
  before_action :correct_user,   only: [:show]

  def create
    if current_user == nil
      flash[:notice] = "Il faut te logger coco"

      redirect_to "/"
    else

      @currentitem = Cartcontent.where(user_id: current_user.id).where(item_id: params[:item_id])[0]

      if @currentitem != nil
        @currentitem.update(quantity: (@currentitem.quantity + 1))
      else
        Cartcontent.create(user_id: current_user.id, item_id: params[:item_id])
      end
      flash[:notice] = "Elément ajouté au panier"

      redirect_to "/"
    end
  end

  def add
    @currentitem = Cartcontent.find(params[:format])
    @currentitem.update(quantity: (@currentitem.quantity + 1))
    redirect_to request.referrer
  end

  def remove
    @currentitem = Cartcontent.find(params[:format])
    @currentitem.update(quantity: (@currentitem.quantity - 1))
    if @currentitem.quantity == 0
      @currentitem.destroy
    end
    redirect_to request.referrer
  end

  def index
    @cartcontents = Cartcontent.all
  end

  def show
    @cartcontent = Cartcontent.where(user_id: params[:id]).order(:item_id)

    @sum = 0
    @cartcontent.each do |cartcontent|
      @sum = ( Item.find(cartcontent.item_id).price * cartcontent.quantity ) + @sum
    end
  end

  def destroy
    Cartcontent.destroy(params[:id])
    redirect_to request.referrer
  end

  private

  def correct_user
    if !user_signed_in?
      redirect_to root_url
    else
      redirect_to root_url unless Cartcontent.where(user_id: current_user.id) == Cartcontent.where(user_id: params[:id])
    end
  end

end

app/helpers/cartcontents_helper.rb
module CartcontentsHelper
end

app/views/cartcontents/_form.html.erb
<%= form_with(model: cartcontent, local: true) do |form| %>
  <% if cartcontent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cartcontent.errors.count, "error") %> prohibited this cartcontent from being saved:</h2>

      <ul>
      <% cartcontent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cartcontents/edit.html.erb
<h1>Editing Cartcontent</h1>

<%= render 'form', cartcontent: @cartcontent %>

<%= link_to 'Show', @cartcontent %> |
<%= link_to 'Back', cartcontents_path %>

app/views/cartcontents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cartcontents</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cartcontents.each do |cartcontent| %>
      <tr>
        <td><%= link_to 'Show', cartcontent %></td>
        <td><%= link_to 'Edit', edit_cartcontent_path(cartcontent) %></td>
        <td><%= link_to 'Destroy', cartcontent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cartcontent', new_cartcontent_path %>

app/views/cartcontents/new.html.erb
<h1>New Cartcontent</h1>

<%= render 'form', cartcontent: @cartcontent %>

<%= link_to 'Back', cartcontents_path %>

app/views/cartcontents/show.html.erb
<div class="cart-show-container">
    <div class="cart-show-list">
        <h2 class="cart-show-list-title">Panier</h2>
            <table>
                <tr>
                    <td class="cart-show-list-item-image-box cart-show-list-columnnames"></td>
                    <td class="cart-show-list-item-title-box cart-show-list-columnnames"></td>
                    <td class="cart-show-list-item-quantity-box cart-show-list-columnnames">Quantité</td>
                    <td class="cart-show-list-item-price-box cart-show-list-columnnames">Prix</td>
                    <td class="cart-show-list-item-button-box cart-show-list-columnnames"></td>
                </tr>
                <% @cartcontent.each do |cartitem|%>
                    <tr>
                        <td class="cart-show-list-item-image-box"><%= link_to (image_tag "photos/#{Item.find(cartitem.item_id).image_url}", class:"cart-show-list-item-image"), item_path(cartitem.item_id)  %></td>
                        <td class="cart-show-list-item-title-box"><%= link_to "#{Item.find(cartitem.item_id).title}", item_path(cartitem.item_id)  %></td>
                        <td class="cart-show-list-item-quantity-box">
                            <%= link_to (image_tag "icons/down.png", class: "cart-show-list-item-quantity-icon"), remove_path(cartitem), method: :post %>
                            <p><%= cartitem.quantity %></p>
                            <%= link_to (image_tag "icons/up.png", class: "cart-show-list-item-quantity-icon"), add_path(cartitem), method: :post %>
                        </td>
                        <td class="cart-show-list-item-price-box"><p><%= Item.find(cartitem.item_id).price %> €</p></td>
                        <td class="cart-show-list-item-delete-box">
                            <div>
                                <%= link_to (image_tag "icons/delete.png", class: "cart-show-list-item-delete-icon"), cartcontent_path(cartitem.id), method: :delete %>
                            </div>
                        </td>
                    </tr>
                <% end %>
            </table>
        <div class="cart-show-list-bottomline">          
            <p></p>
            <%= form_tag orders_path(current_user) do %>
              <article>
                <% if flash[:error].present? %>
                  <div id="error_explanation">
                    <p><%= flash[:error] %></p>
                  </div>
                <% end %>
                <label class="amount">
                    <span><%= "Payer: #{@sum} €" %></span>
                </label>
              </article>
                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                      data-locale="auto"></script>
            <% end %>
        </div>
    </div>
</div>






 