config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'items#index'
  resources :items, param: :slug
  resources :charges, :cartcontents, :orders
  post "add", to: "cartcontents#add"
  post "remove", to: "cartcontents#remove"
  get '/mail', to: 'items#mail'
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cartcontents
  has_many :users, through: :cartcontents
  has_many :itemcats
  has_many :categories, through: :itemcats

  def self.add_slugs
    update(slug: to_slug(name))
  end

  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, :description, :price, :image_url, presence: true

  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    if params[:format] == nil
      @current_category = "Tous"
      @item = Item.all
    else
      @current_category = Category.find(params[:format]).name
      @item = []
      Itemcat.where(category_id: params[:format]).each do |item|
        @item << Item.find(item.item_id)
      end
    end
  end

  def show
    @item = Item.find_by_slug(params[:slug])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<!-- Banner -->
<section class="banner">
    <h1 class="banner-title">Bienvenue sur le site des miaous à bas prix !</h1>
    <p class="banner-text">Ici tu trouveras de quoi dépenser ton pognon durement gagné dans ton travail d'employé, et vieux jte le dis acheter un miaou c'est méga mieux que zoner à Chatelet et finir avec une bougie pomme-canelle de chez Maison du Monde. Alleer, fais toi plaisir !</p>
</section>

<!-- left: 70%; -->


<!-- Banner selector -->
<div class="selector-box">
    <p>Catégorie :</p>
    <div class="selector selector-title-box">
        <p class="selector-title"><%= @current_category %></p>
    
        <div class="selector-content">
            <% if @current_category == "Tous" %>
                <%= link_to "Tous", items_path, method: :get, class: "selector-content-current" %>
            <% else %>
                <%= link_to "Tous", items_path, method: :get %>
            <% end %>
            <% Category.all.each do |category| %>
                <% if @current_category == category.name %>
                    <%= link_to category.name, items_path(category.id), method: :get, class: "selector-content-current" %>
                <% else %>
                    <%= link_to category.name, items_path(category.id), method: :get %>
                <% end %>
            <% end %>
        </div>
    </div>
</div>


<!-- Cards -->
<section class="items-index-container">
    <% @item.each do |item|%>
        <div class="card">
            <%= link_to item_path(item.slug) do  %>
                <%= image_tag "photos/#{item.image_url}", class:"card-image"%>
                <div class="card-price-container">
                    <%= image_tag "icons/star-shape-price.png", class:"card-price-icon"%>
                    <p class="card-price-text"><%= item.price %> €</p>
                </div>
            <% end %>
        </div>
    <% end %>
</section>

app/views/items/mail.html.erb
ceci est un test

app/views/items/show.html.erb
<div class="items-show-container">
    <%= image_tag "photos/#{@item.image_url}", class:"show-photo"%>
    <div class="show-container-right">
        <h2 class="show-title"><%= @item.title %></h2>
        <p class="show-description"><%= @item.description %></p>
        <p class="show-price"><%= @item.price %> €</p>
        <%= button_to "Ajouter au panier", cartcontents_path(@item), :params => {:item_id => @item.id}, class: "button" %>
        <div class="return">
            <%= link_to "Retour", "/", method: :get %>
        </div>
    </div>
</div>